### ISSUE TITLE
pytorch版本问题

### ISSUE THREAD

**Issue by surrerendpity** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#27]
Traceback (most recent call last):
  File "D:/Users/admin computer/PycharmProjects/Fatigue-Driven-Detection-Based-on-CNN-master/camera_detection.py", line 82, in <module>
    torch.cat([o.view(-1,4) for o in priors],0)
  File "D:\Users\anaconda3\envs\tf21\lib\site-packages\torch\autograd\function.py", line 160, in __call__
    "Legacy autograd function with non-static forward method is deprecated. "
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

在camera_detection.py中Detect函数实例化为detect，然后使用的时候出错。
查了一下原因如下：由于你当前的pytorch版本过高，而原代码的版本较低。如果pytorch版本高于1.3会出现该问题。当前版本要求forward过程是静态的，所以需要将原代码进行修改。我pytorch版本为1.7.1，要降版本还要重装cuda非常麻烦。可以问一下是否有办法通过改代码解决呢？照网上的方法改不成功

**Comment by PengfeiM** [comment]
按照这里的描述把自动梯度函数换成新的应该就行了吧。

后面几个版本的我没太关注。你可以试试。

发件人: surrerendpity ***@***.***>
发送时间: 2022年3月17日 23:41
收件人: PengfeiM/Fatigue-Driven-Detection-Based-on-CNN ***@***.***>
抄送: Subscribed ***@***.***>
主题: [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN] pytorch版本问题 (Issue #27)


Traceback (most recent call last):
File "D:/Users/admin computer/PycharmProjects/Fatigue-Driven-Detection-Based-on-CNN-master/camera_detection.py", line 82, in
torch.cat([o.view(-1,4) for o in priors],0)
File "D:\Users\anaconda3\envs\tf21\lib\site-packages\torch\autograd\function.py", line 160, in call
"Legacy autograd function with non-static forward method is deprecated. "
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

在camera_detection.py中Detect函数实例化为detect，然后使用的时候出错。
查了一下原因如下：由于你当前的pytorch版本过高，而原代码的版本较低。如果pytorch版本高于1.3会出现该问题。当前版本要求forward过程是静态的，所以需要将原代码进行修改。我pytorch版本为1.7.1，要降版本还要重装cuda非常麻烦。可以问一下是否有办法通过改代码解决呢？照网上的方法改不成功

**Comment by surrerendpity** [comment]
看官方教程用apply函数终于解决了，初学真不容易啊。谢谢作者的分享

**Comment by wql-uestc** [comment]
> Traceback (most recent call last): File "D:/Users/admin computer/PycharmProjects/Fatigue-Driven-Detection-Based-on-CNN-master/camera_detection.py", line 82, in torch.cat([o.view(-1,4) for o in priors],0) File "D:\Users\anaconda3\envs\tf21\lib\site-packages\torch\autograd\function.py", line 160, in **call** "Legacy autograd function with non-static forward method is deprecated. " RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
> 
> 在camera_detection.py中Detect函数实例化为detect，然后使用的时候出错。 查了一下原因如下：由于你当前的pytorch版本过高，而原代码的版本较低。如果pytorch版本高于1.3会出现该问题。当前版本要求forward过程是静态的，所以需要将原代码进行修改。我pytorch版本为1.7.1，要降版本还要重装cuda非常麻烦。可以问一下是否有办法通过改代码解决呢？照网上的方法改不成功

同学，请问一下用apply函数如何解决呢
