### ISSUE TITLE
运行train时报错

### ISSUE THREAD

**Issue by ChrisZ-123** [PengfeiM/Fatigue-Driven-Detection-Based-on-CNN#50]
default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ..\torch\csrc\tensor\python_tensor.cpp:453.)
  _C._set_default_tensor_type(t)
Traceback (most recent call last):
  File "c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\Train.py", line 111, in <module>
    train()
  File "c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\Train.py", line 84, in train
    for step,(img,target) in enumerate(data_loader):
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\voc0712.py", line 111, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\voc0712.py", line 130, in pull_item
    img, boxes, labels = self.transform(img, target[:, :4], target[:, 4])
  File "c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\augmentations.py", line 416, in __call__
    return self.augment(img, boxes, labels)
  File "c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\augmentations.py", line 51, in __call__
    img, boxes, labels = t(img, boxes, labels)
  File "c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\augmentations.py", line 237, in __call__
    mode = random.choice(self.sample_options)
  **File "numpy\\random\\mtrand.pyx", line 936, in numpy.random.mtrand.RandomState.choice
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.**

**Comment by xiaozhang1017** [comment]
> default_dtype() 和 torch.set_default_device() 作为替代方案。 （在 ..\torch\csrc\tensor\python_tensor.cpp:453 内部触发。） _C._set_default_tensor_type(t) 回溯（最近一次调用）： 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection -基于 CNN-master\Train.py”，第 111 行， train() 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\Train.py” ，第 84 行，在 枚举（data_loader）中的步骤（img，目标）中： 文件“C：\ Users \ Lenovo \ AppData \ Roaming \ Python \ Python310 \ site-packages \ torch \ utils \ data \ dataloader.py ”，第 630 行，下**一个** data = self._next_data() 文件“C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py”，第 674 行，在_next_data data = self._dataset_fetcher.fetch(index) # 可能会引发 StopIteration File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data_utils\fetch.py​​", line 51,在 fetch data = [self.dataset[idx] for idx in possible_batched_index] 文件“C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data_utils\fetch.py​​”，第 51 行，在 data = [self.dataset[idx] for idx in possible_batched_index] 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\voc0712.py”，第 111 行，在**getitem** im, gt, h, w = self.pull_item(index) 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\voc0712.py”，第 130 行，在 pull_item 中 img, box, labels = self.transform(img, target[:, :4], target[:, 4]) 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN- master\augmentations.py”，第 416 行，**调用**中 返回 self.augment(img,boxes, labels) 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\augmentations. py”，第 51 行，调用**img** ,boxes, labels = t(img,boxes,labels) 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\augmentations.py ”，第 237 行，在**调用** 模式 = random.choice(self.sample_options) **文件“numpy\random\mtrand.pyx”，第 936 行，在 numpy.random.mtrand.RandomState.choice ValueError：用序列设置数组元素。请求的数组在 1 维之后具有不均匀的形状。检测到的形状为(6,)+不均匀部分。**

@ChrisZ-123 我也有这个问题，你是否已经成功解决了？
![0%IJ9BILG8IKJ{F{1VIPGO1](https://github.com/PengfeiM/Fatigue-Driven-Detection-Based-on-CNN/assets/156777560/9d5edace-0d6b-4f02-a3f3-c3163cc87e44)

**Comment by xiaozhang1017** [comment]
> > default_dtype() 和 torch.set_default_device() 作为替代方案。 （在 ..\torch\csrc\tensor\python_tensor.cpp:453 内部触发。） _C._set_default_tensor_type(t) 回溯（最近一次调用）： 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection -基于 CNN-master\Train.py”，第 111 行， train() 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\Train.py” ，第 84 行，在 枚举（data_loader）中的步骤（img，目标）中： 文件“C：\ Users \ Lenovo \ AppData \ Roaming \ Python \ Python310 \ site-packages \ torch \ utils \ data \ dataloader.py ”，第 630 行，下**一个** data = self._next_data() 文件“C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data\dataloader.py”，第 674 行，在_next_data data = self._dataset_fetcher.fetch(index) # 可能会引发 StopIteration File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data_utils\fetch.py​​", line 51,在 fetch data = [self.dataset[idx] for idx in possible_batched_index] 文件“C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\torch\utils\data_utils\fetch.py​​”，第 51 行，在 data = [self.dataset[idx] for idx in possible_batched_index] 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\voc0712.py”，第 111 行，在**getitem** im, gt, h, w = self.pull_item(index) 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\voc0712.py”，第 130 行，在 pull_item 中 img, box, labels = self.transform(img, target[:, :4], target[:, 4]) 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN- master\augmentations.py”，第 416 行，**调用**中 返回 self.augment(img,boxes, labels) 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\augmentations. py”，第 51 行，调用**img** ,boxes, labels = t(img,boxes,labels) 文件“c:\Users\Lenovo\Desktop\Fatigue-Driven-Detection-Based-on-CNN-master\augmentations.py ”，第 237 行，在**调用** 模式 = random.choice(self.sample_options) **文件“numpy\random\mtrand.pyx”，第 936 行，在 numpy.random.mtrand.RandomState.choice ValueError：用序列设置数组元素。请求的数组在 1 维之后具有不均匀的形状。检测到的形状为(6,)+不均匀部分。**
> 
> @ChrisZ-123 我也有这个问题，你是否已经成功解决了？ ![0%IJ9BILG8IKJ{F{1VIPGO1](https://private-user-images.githubusercontent.com/156777560/320851998-9d5edace-0d6b-4f02-a3f3-c3163cc87e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Njg1NDAsIm5iZiI6MTcxMjY2ODI0MCwicGF0aCI6Ii8xNTY3Nzc1NjAvMzIwODUxOTk4LTlkNWVkYWNlLTBkNmItNGYwMi1hM2YzLWMzMTYzY2M4N2U0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxMzEwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGI1ZDlmMWJiNTBlMWRkMmZmN2FkZDFjYTczZDhhYWJhOWUxYmM5NDk4MjcxZjkyZGMwZWI5ODYyZTVhZjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bnU6Fsg0cUlb_JnTDSycOQxqUsI2UZhLVyJpyw08vAE)

我发现报错是numpy版本问题。
解决办法：
卸载现有版本numpy，安装numpy 1.21.0(python 3.6)版本或者1.23.5(python 3.11)
 pip install numpy==1.21.0或者pip install numpy==1.23.5

**Comment by Yunone1** [comment]
D:\Anaconda3\envs\tensorflow-gpu\python.exe D:\mybs\Fatigue-Driven-Detection-Based-on-CNN-master\Train.py 
Traceback (most recent call last):
  File "D:\mybs\Fatigue-Driven-Detection-Based-on-CNN-master\Train.py", line 111, in <module>
    train()
  File "D:\mybs\Fatigue-Driven-Detection-Based-on-CNN-master\Train.py", line 61, in train
    Config.MEANS))
  File "D:\mybs\Fatigue-Driven-Detection-Based-on-CNN-master\voc0712.py", line 107, in __init__
    for line in open(osp.join(rootpath, 'ImageSets', 'Main', name + '.txt')):
FileNotFoundError: [Errno 2] No such file or directory: './dataset/ImageSets\\Main\\trainval.txt'

**Comment by Rockylix** [comment]
此问题应为numpy版本的问题，我采用了numpy 2.0.2版本，对数组格式要求更严格，在argumentation.py中更改了如下代码，
def __init__(self):
        self.sample_options = [
            (0.1, 1.0),    # 最小 IoU 0.1
            (0.3, 1.0),    # 最小 IoU 0.3
            (0.7, 1.0),    # 最小 IoU 0.7
            (0.9, 1.0),    # 最小 IoU 0.9
            (0.0, 1.0)     # 随机采样
        ]

    def __call__(self, image, boxes=None, labels=None):
        height, width, _ = image.shape
        while True:
            mode = np.random.choice(len(self.sample_options))
            min_iou, max_iou = self.sample_options[mode]
